config/routes.rb
Hack::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  # queue background web monitor
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["ADMIN"] && password == ENV["ADMIN_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  resources :pages, only: [:index] do
    collection do
      get :welcome, as: 'welcome'
      post :add_airport_form
      post :remove_airport_form
    end
  end

  root 'pages#index'

  get 'auth/:provider/callback', to: 'session#create'
  delete '/signout', to: 'session#destroy', as: 'signout'

  get 'auth/failure', to: redirect('/')

  resources :users, only: [:edit, :update]

  resources :airports, only: [] do
    collection do
      get :autocomplete
      get :geocode
    end
  end

  resources :wishlists, only: [:create, :index] do
    member do
      put :update_sms_state
      post :sms
    end

    collection do
      post :polling_charge
    end
  end

  get "/ical/:token", to: "wishlists#ical", as: :ical
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def create
    @user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = @user.id
    if @user.mobile.present?
      redirect_to root_url
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Signed out!"
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/create.html.slim
h1 Session#create
p Find me in app/views/session/create.html.slim

app/views/session/destroy.html.slim
h1 Session#destroy
p Find me in app/views/session/destroy.html.slim

app/views/session/edit.html.slim
= form_tag update_user_path(@user), method: :put
  = text_field_tag "user[mobile]", "#{@user.mobile}", placeholder: "Please enter your mobile number"
  = submit_tag 'Go'