config/routes.rb
Hack::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  # queue background web monitor
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["ADMIN"] && password == ENV["ADMIN_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  resources :pages, only: [:index] do
    collection do
      get :welcome, as: 'welcome'
      post :add_airport_form
      post :remove_airport_form
    end
  end

  root 'pages#index'

  get 'auth/:provider/callback', to: 'session#create'
  delete '/signout', to: 'session#destroy', as: 'signout'

  get 'auth/failure', to: redirect('/')

  resources :users, only: [:edit, :update]

  resources :airports, only: [] do
    collection do
      get :autocomplete
      get :geocode
    end
  end

  resources :wishlists, only: [:create, :index] do
    member do
      put :update_sms_state
      post :sms
    end

    collection do
      post :polling_charge
    end
  end

  get "/ical/:token", to: "wishlists#ical", as: :ical
end

app/models/airport.rb
# == Schema Information
#
# Table name: airports
#
#  id           :integer          not null, primary key
#  airport_id   :string(255)
#  airport_name :string(255)
#  city_id      :string(255)
#  city_name    :string(255)
#  country_id   :string(255)
#  country_name :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  latitude     :float
#  longitude    :float
#

class Airport < ActiveRecord::Base
  searchkick autocomplete:
    [:airport_name, :city_name, :country_name]

  # For ELASTIC SEARCH
  # def self.autocomplete(query, limit: 10)
  #   self.search(query, autocomplete: true, limit: limit).map(&:prettify)
  # end

  def self.autocomplete(query, limit: 10)
    start_query = "#{query.downcase}%"
    where("airport_name LIKE ? OR city_name LIKE ? OR country_name LIKE ?",
      start_query, start_query, start_query).limit(limit).map(&:prettify)
  end

  def prettify
    "#{airport_name}, #{city_name}, #{country_name}"
  end

  def self.find_by_full(query)
    airport_name = query.split(", ").first
    airport = self.where(airport_name: airport_name).first

    airport.fetch_again
    airport
  end

  def self.find_city_id(city)
    where(city_name: city).first.city_id
  end

  def self.find_city_id_by_query(query)
    city_name = query.split(", ").second
    self.find_city_id city_name
  end

  geocoded_by :prettify
  after_validation :geocode

  # SO SHIT
  def fetch_again
    unless self.latitude
      self.latitude, self.longitude = Geocoder.coordinates(self.prettify)
      self.save
    end
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def autocomplete
    render json: Airport.autocomplete(params[:query])
  end

  def geocode
    render json: Airport.find_by_full(params[:airport])
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/views/airports/_location_input.html.slim
.form-group.location-input
  .input-group.input-group-lg
    span.input-group-addon
      a.fa.fa-sort
    = text_field_tag :query, params[:query], class: "form-control search-query", autocomplete: "off", placeholder: "Tell us where you want to travel ;)"
    .input-group-btn
      = link_to "clear", "#", class: "clear-text btn btn-warning"
  br

app/views/airports/_map.html.erb
<div id="map" style="height: 400px;"></div>

<%= content_for :google_map do %>
  <script type="text/javascript"
    src="//maps.googleapis.com/maps/api/js?sensor=false"></script>

  <script>
    $(function() {
      var mapper = new MapApp.Mapper('#map');

      $('[data-latitude]').each(function(index, element) {
        mapper.addCoordinates(
          $(element).attr('data-latitude'),
          $(element).attr('data-longitude')
        );
      });

      mapper.render();
    });

    $(function() {
      if (_.isEmpty($('#search_value').attr('placeholder'))) {
        var currentLocation = new MapApp.CurrentLocation();
        currentLocation.getLocation(function(location) {
          $('#search_value').attr('placeholder', location);
        })
      }
    });
  </script>
<% end %>

app/views/airports/_search_form.html.slim
= form_tag url_for, class: "form-inline form-horizontal", method: :get do

  .form-group
    .input-group.input-group-lg
      = text_field_tag :name, params[:name], class: "form-control", autocomplete: "off", placeholder: "Give your trip an awesome name!"
      .input-group-btn
        = link_to "Hmmm", "#", class: "clear-text btn btn-warning"
    br

    .input-group.input-group-lg.date
      span.input-group-addon
        a.fa.fa-calendar
      = text_field_tag :start_at, params[:start_at], class: "form-control", placeholder: "When do you start your trip?"
      .input-group-btn
        = link_to "Clear", "#", class: "clear-text btn btn-warning"
    br

    .input-group.input-group-lg
      span.input-group-addon
        a.fa.fa-gbp
      = text_field_tag :budget, params[:budget], class: "form-control", placeholder: "That's fine if your budget is tight."
      .input-group-btn
        = link_to "Clear", "#", class: "clear-text btn btn-warning"
    br

  .search-form-group
    = render 'airports/location_input'

  .form_group
      br
      .btn-group
        = link_to add_airport_form_pages_path, class: "btn btn-success", remote: true, method: :post do
          i.fa.fa-plus-square.fa-1
      .btn-group
        = link_to remove_airport_form_pages_path, class: "btn btn-danger",remote: true, method: :post do
                i.fa.fa-minus-square.fa-1
      .btn-group.pull-right
        = button_tag :wish_btn, class: "btn btn-primary wishlist" do
          i.fa.fa-plane.fa-lg
          | &nbsp;&nbsp;&nbsp;Let's GO!

#modal-place

app/views/airports/autocomplete.html.slim
h1 Airports#autocomplete
p Find me in app/views/airports/autocomplete.html.slim