config/routes.rb
Hack::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  # queue background web monitor
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["ADMIN"] && password == ENV["ADMIN_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  resources :pages, only: [:index] do
    collection do
      get :welcome, as: 'welcome'
      post :add_airport_form
      post :remove_airport_form
    end
  end

  root 'pages#index'

  get 'auth/:provider/callback', to: 'session#create'
  delete '/signout', to: 'session#destroy', as: 'signout'

  get 'auth/failure', to: redirect('/')

  resources :users, only: [:edit, :update]

  resources :airports, only: [] do
    collection do
      get :autocomplete
      get :geocode
    end
  end

  resources :wishlists, only: [:create, :index] do
    member do
      put :update_sms_state
      post :sms
    end

    collection do
      post :polling_charge
    end
  end

  get "/ical/:token", to: "wishlists#ical", as: :ical
end

app/models/wishlist.rb
# == Schema Information
#
# Table name: wishlists
#
#  id         :integer          not null, primary key
#  settings   :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#  start_at   :date
#  end_at     :date
#  state      :boolean
#  name       :string(255)
#  budget     :decimal(8, 2)
#  result     :text
#  sms_state  :boolean
#

class Wishlist < ActiveRecord::Base

  store :settings, accessors: [:cities, :stays]
  store :result, accessors: [:given_routes, :given_plans]

  belongs_to :user

  default_scope order('updated_at DESC')

  def city_names
    cities.map do |city|
      Airport.find_by(id: city).prettify
    end
  end

  def self.save_with_cities(cities)
    city_ids = cities.map do |city|
      Airport.find_by_full(city).id
    end

    self.create cities: city_ids
  end

  def prettify_state
    state ? "Got it!" : "Wait, wait! We are still working hard on this :)"
  end

  before_save do |list|

    list.token = SecureRandom.uuid.delete('-') unless list.token
    list.name = "An Unamed Wish List" if list.name == "" || list.name == nil

    # default is false
    list.state = false
    list.sms_state ||= false

    # save the date
    list.start_at ||= Date.today + 5.day
    list.end_at ||= Date.today + 5.day

    # city list init, so dirty
    unless list.cities
      list.cities = []
      list.stays = []
    end

    if list.cities.length == list.stays.try(:length)
      list.stays.each do |stay|
        stay = 0 unless stay
      end
    else
      list.stays = [0] * list.cities.length
    end

    # init the budget, given_plan and given_routes. Well, I know it's too nasty though.
    list.budget = 1000 if list.budget.nil? || list.budget == ""

    list.given_routes ||= []
    list.given_plans ||= []
    list.state = true if list.given_routes.length > 0
  end

  def self.newly_completed(*indexes)
    where("id IN (?) and state = ?", indexes, true).to_a
  end
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

  before_action :can_visit?, except: [:ical]

  def index
    @wishlists = current_user.wishlists.all
  end

  def create
    return render json: {success: false} unless params[:cities]

    @wishlist = Wishlist.save_with_cities params[:cities]
    @wishlist.update_attributes(
      user: current_user,
      name: params[:name],
      start_at: params[:start_at],
      budget: params[:budget]
      )

    # Here you are
    BestRoutesWorker.perform_async @wishlist.id if @wishlist

    respond_to do |format|
      format.js
    end
  end

  def update_sms_state
    @wishlist = Wishlist.find_by_id params[:id]
    @wishlist.update_attributes sms_state: true

    respond_to do |format|
      format.js
    end
  end

  def sms
    SMSWorker.perform_async params[:id]
    @wishlist = Wishlist.find_by id: params[:id]
    respond_to do |format|
      format.js
    end
  end

  def polling_charge
    @wishlists = Wishlist.newly_completed *params[:uncompleted].map(&:to_i)

    result = @wishlists.map do |wishlist|
      {
        id: wishlist.id,
        html: render_to_string(partial: "wishlists/completed_wishlist", layout: false,
          locals: {wishlist: wishlist})
      }
    end

    render json: result
  end

  def ical
    wishlist = Wishlist.find_by(token: params[:token])
    return render json: "No such calendar" unless wishlist
    ical = Ical.new wishlist
    render text: ical.generate!, content_type: 'text/calendar'
  end
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_completed_wishlist.html.slim
.panel.panel-default
  .panel-heading
    h4.panel-title
      = link_to "#wishlist#{wishlist.id}", "data-parent" => "#accordion", "data-toggle" => "collapse" do
        = "#{wishlist.name} is ready for you!!!"
        i.fa.fa-check-circle-o.pull-right
  = content_tag :div, id: "wishlist#{wishlist.id}", class: "panel-collapse collapse" do
    .panel-body
      / - wishlist.given_plans.each do |plan|
      /   ul
      /     li.lead
      /       = "From #{plan["Origin"]} to #{plan["Destination"]} via #{plan["Carrier"]} at #{plan["DepartureDate"]}, which takes you #{gbp(plan["MinPrice"])}!"
      table.table.table-striped
        thead
          tr
            th #
            th Origin
            th Destination
            th Carrier
            th Departure Date
            th Price
        tbody
          - wishlist.given_plans.each_with_index do |plan, index|
            tr
              td
                = index + 1
              td
                = plan["Origin"]
              td
                = plan["Destination"]
              td
                = plan["Carrier"]
              td
                = plan["DepartureDate"]
              td
                = gbp(plan["MinPrice"])
      .pull-right
        - if wishlist.sms_state
          = link_to "Have not received?", sms_wishlist_path(wishlist), remote: true, method: :post, class: "btn btn-success", id: "text-me-again-#{wishlist.id}"

        = link_to "Can I add it to my calendar?", "#", class: "btn btn-primary tell-me-ical", "data-secret" => "#{ENV["SITE"]}ical/#{wishlist.token}"

app/views/wishlists/_success_modal.html.slim
#successModal.modal.fade aria-hidden="true" aria-labelledby="successModalLabel" role="dialog" tabindex="-1"
  .modal-dialog
    .modal-content
      .modal-header
        button.close aria-hidden="true" data-dismiss="modal" type="button"
        h4#successModalLabel.modal-title Thank you for being awesome!
      .modal-body
        p.lead
          = "Currently we are working hard on your trip, #{@wishlist.name}. We are very willing to tell you how wonderful it is as fast as we can ;)"
      .modal-footer
        = link_to "Text me about that!", update_sms_state_wishlist_path(@wishlist), remote: true, method: :put, class: "btn btn-success", id: "text-me"
        = link_to "What's other people's choice?", wishlists_path, class: "btn btn-primary"

app/views/wishlists/_uncompleted_wishlist.html.slim
= content_tag :div, class: "panel panel-default uncompleted", id: "uncompleted-#{wishlist.id}", "data-id" => "#{wishlist.id}" do
  .panel-heading
    h4.panel-title
      = link_to "#wishlist#{wishlist.id}", "data-parent" => "#accordion", "data-toggle" => "collapse" do
        = "We are still working hard on #{wishlist.name} ;)"
        i.fa.fa-cog.fa-spin.pull-right
  = content_tag :div, id: "wishlist#{wishlist.id}", class: "panel-collapse collapse" do
    .panel-body
      | Wait wait wait...

app/views/wishlists/create.html.slim
h1 Wishlists#create
p Find me in app/views/wishlists/create.html.slim

app/views/wishlists/create.js.erb
$("<%= escape_javascript(render 'wishlists/success_modal') %>").appendTo("#modal-place")
$('#successModal').modal('toggle')

app/views/wishlists/index.html.slim
.row
  .col-lg-12
    h1.lead Your Awesome Wish Lists
    hr

    #accordion.panel-group.wishlists
      - @wishlists.each do |wish|
        - if wish.state
          = render :partial => "wishlists/completed_wishlist", :locals => { :wishlist => wish }
        - else
          = render :partial => "wishlists/uncompleted_wishlist", :locals => { :wishlist => wish }

app/views/wishlists/sms.js.erb
$("#text-me-again-<%= @wishlist.id %>").replaceWith('<button class="btn btn-success disabled"><i class="fa fa-thumbs-o-up"></i>&nbsp;&nbsp;&nbsp;Okay!</button>')

app/views/wishlists/update_sms_state.js.erb
$("#text-me").replaceWith('<button class="btn btn-success disabled"><i class="fa fa-thumbs-o-up"></i>&nbsp;&nbsp;&nbsp;Yes, Sir!</button>')