config/routes.rb
Hack::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  # queue background web monitor
  require 'sidekiq/web'
  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    username == ENV["ADMIN"] && password == ENV["ADMIN_PASSWORD"]
  end

  mount Sidekiq::Web => '/sidekiq'

  resources :pages, only: [:index] do
    collection do
      get :welcome, as: 'welcome'
      post :add_airport_form
      post :remove_airport_form
    end
  end

  root 'pages#index'

  get 'auth/:provider/callback', to: 'session#create'
  delete '/signout', to: 'session#destroy', as: 'signout'

  get 'auth/failure', to: redirect('/')

  resources :users, only: [:edit, :update]

  resources :airports, only: [] do
    collection do
      get :autocomplete
      get :geocode
    end
  end

  resources :wishlists, only: [:create, :index] do
    member do
      put :update_sms_state
      post :sms
    end

    collection do
      post :polling_charge
    end
  end

  get "/ical/:token", to: "wishlists#ical", as: :ical
end

app/views/layouts/_sign_bar.html.slim
ul.nav.navbar-nav.navbar-right
  - if current_user
    li
      = link_to "Signed in as #{current_user}", edit_user_path(current_user)
    li
      = link_to "Sign Out", signout_path, method: :delete
  - else
    li
      = link_to "Sign in with Twitter", "/auth/twitter"
    li
      = link_to "Sign in with Facebook", "/auth/facebook"

app/views/layouts/application.html.slim
doctype 5
html(lang="en")
  head
    meta(charset="utf-8")
    meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    meta(name="viewport" content="width=device-width, initial-scale=1.0")
    title= content_for?(:title) ? yield(:title) : "hack"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "application", :media => "all"
    = yield(:page_stylesheet) if content_for?(:page_stylesheet)

  body
    .navbar.navbar-default.navbar-fixed-top
      .container
        .navbar-header
        a.navbar-brand href="/"
          | Sky Omakase
        #navbar-main.navbar-collapse.collapse
          ul.nav.navbar-nav
            - if current_user
              li
                = link_to "My Wishlist", wishlists_path
            li
              = link_to "Our Story", "http://jaxihjk.me"
            li
              = link_to "Get Source", "https://github.com/jaxi/hack"
          = render 'layouts/sign_bar'
    .container
      #banner.page-header
        == yield

    = javascript_include_tag "application"
    = render "application/google_analytics"
    = yield :google_map